version: "3.5"

networks:
  duplicacy_cli:

volumes:
  duplicacy_cli:

secrets:
  duplicacy_cli_repo_password:
    name: ${STACK_NAME:-technocore}_duplicacy_cli_repo_password
    external: true
  duplicacy_cli_storage_username:
    name: ${STACK_NAME:-technocore}_duplicacy_cli_storage_username
    external: true
  duplicacy_cli_storage_password:
    name: ${STACK_NAME:-technocore}_duplicacy_cli_storage_password
    external: true

services:
  ## Uncomment this if Traefik will be used for routing traffick to this service.
  #ingress:
  #  networks:
  #    - duplicacy_cli

  duplicacy_cli:
    deploy:
      labels:
      #  - traefik.frontend.rule=$DUPLICACY_CLI_ROUTING_LABEL
      #  - traefik.frontend.priority=$DUPLICACY_CLI_ROUTING_LABEL_PRIORITY
      #  # You'll need to set application's port here.
      #  - traefik.port=SET_ME_PLEASE
      #  - ${TRAEFIK_BASIC_AUTH}
      #  - traefik.enable=true
      #  - traefik.tags=ingress 
      #  - traefik.docker.network=${STACK_NAME:-technocore}_duplicacy_cli
      #  # Traefik service that listens to HTTP
      #  - traefik.redirectorservice.frontend.entryPoints=http
      #  - traefik.redirectorservice.frontend.redirect.entryPoint=https
      #  # Traefik service that listens to HTTPS
      #  - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
        - user-provided-secret-repo_password=duplicacy_cli repo_password
        - user-provided-secret-storage_username=duplicacy_cli storage_username
        - user-provided-secret-storage_password=duplicacy_cli storage_password
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      # Run within 45 minutes.
      - JOB_RANDOM_DELAY=${DUPLICACY_JOB_RANDOM_DELAY:-2700}
      #- RUN_JOB_IMMEDIATELY=yes
      - STORAGE_URL=${DUPLICACY_STORAGE_URL:-PLEASE_ENTER_A_DUPLICACY_STORAGE_URL}
      - "FILTER_PATTERNS=
        -*/.snapshots/;
        -*.sock;
        -*.pipe;
        +root/${TECHNOCORE_DATA}/*;
        -root/home/*/.config/libreoffice/*/user/uno_packages/cache/*;
        -root/home/*/.config/deluge/ipc/deluge-gtk;
        -root/home/*/.cache/*;
        -root/home/*/.var/app/*/cache/*;
        -root/home/*/.cache/mozilla/*;
        -root/home/*/.cache/chromium/*;
        -root/home/*/.cache/BraveSoftware/*;
        -root/home/*/.local/share/Trash/*;
        -root/home/*/.gvfs/*;
        -root/home/*/.thumbnails/*;
        +root/home/*;
        -root/var/lib/docker/*;
        -root/var/lib/flatpak/*;
        -root/var/lib/nfs/rpc_pipefs/gssd/clntXX/gssd;
        -root/var/run/*;
        -root/var/lock/*;
        -root/var/log/*;
        -root/var/cache/apt/archives/*;
        -root/var/cache/*;
        -root/var/crash/*;
        -root/var/spool/squid/*;
        -root/var/tmp/*;
        +root/var/*;
        -root/etc/systemd/system.control/*;
        +root/etc/*;
        -root/usr/share/hassio/media/*;
        -root/usr/share/hassio/share/downloads/*;
        +root/usr/share/*;
        +root/usr/local/*;
        +root/usr/;
        -root/usr/*;
        +root/opt/*;
        -root/root/.cache/*;
        +root/root/*;
        +root/;
        -root/*;"
      - EMAIL_TO=${DUPLICACY_EMAIL_TO}
      - HEALTH_CHECK_URL=${DUPLICACY_HEALTH_CHECK_URL}
      - $DUPLICACY_POST_BACKUP_SCRIPT
      #- POST_BACKUP_SCRIPT=/usr/bin/ping_url.sh
      - DUPLICACY_PASSWORD={{"{{DOCKER-SECRET:repo_password}}"}}
      - DUPLICACY_WASABI_KEY={{"{{DOCKER-SECRET:storage_username}}"}}
      - DUPLICACY_WASABI_SECRET={{"{{DOCKER-SECRET:storage_password}}"}}
      # Backup hourly
      - "BACKUP_CRON=${DUPLICACY_BACKUP_CRON:-0 1 * * *}"
      # Prune nightly
      - PRUNE_CRON=${DUPLICACY_PRUNE_CRON:-0 1 * * *}
      - PRUNE_KEEP_POLICIES=${DUPLICACY_PRUNE_KEEP_POLICIES:-7:90;30:180;0:360}
      #- PRUNE_OPTIONS=
      - SNAPSHOT_ID=${HOST_HOSTNAME}
      - EMAIL_HOSTNAME_ALIAS=${HOST_HOSTNAME}
      - EMAIL_FROM=${TECHNOCORE_SMTP_ADDRESS:-technocore@$DOMAIN}
      - "EMAIL_FROM_NAME=Duplicacy: $HOST_HOSTNAME"
      - EMAIL_SMTP_SERVER=smtp_relay
      - EMAIL_SMTP_SERVER_PORT=587
    image: ${image_provider:-scififarms}/technocore-duplicacy-cli:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - duplicacy_cli
    secrets:
      - source: duplicacy_cli_repo_password
        target: repo_password
      - source: duplicacy_cli_storage_username
        target: storage_username
      - source: duplicacy_cli_storage_password
        target: storage_password

    # IF YOU UPDATE THESE, ALSO UPDATE duplicacy-gui!
    volumes:
      - ${TECHNOCORE_DATA}/:/data/technocore_data:ro
      - /:/data/root:ro
